# Generated by Django 2.0.2 on 2018-02-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=100)),
                ('cilindraje', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('apelidos', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('campeonatos', models.ManyToManyField(blank=True, null=True, to='Moto.Campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='moto',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moto.Piloto'),
        ),
        migrations.AddField(
            model_name='moto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moto.Marca'),
        ),
    ]
